AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
Layout/LineLength:
  Enabled: true
  Max: 120
Style/Documentation:
  Enabled: false
